const ActionTypes = {
  START_GET_DATA: 'START_GET_DATA',
  DONE_GET_DATA: 'DONE_GET_DATA',
  GOT_SENSOR_DATA: 'GOT_SENSOR_DATA',
  DONE_GET_MENU: 'DONE_GET_MENU',
  GOT_MENU_UPDATES: 'GOT_MENU_UPDATES',
  MQTT_MESSAGE_ARRIVED: 'MQTT_MESSAGE_ARRIVED'
}

export default ActionTypes